### ISSUE TITLE
500 itprism ui not found while click projects

### ISSUE THREAD

**Issue by bwilliaml** [ITPrism/CrowdFunding#100]
![error project](https://f.cloud.github.com/assets/3913092/2205901/cf7f6bb0-9957-11e3-9b07-39df03e7e718.png)

**Comment by hemantphp** [comment]
Hi,

I have installed vip portfolio joomla extenstion for website. I have getting error "itprism ui not found. ". I can't find document to how to install 'itprism' lib. 

Could you pls. guide for install 'itprism' for joomla 3 version.?
