### ISSUE TITLE
theme template 

### ISSUE THREAD

**Issue by jiyuchen** [ITPrism/CrowdFunding#114]
Hi,
 can you advise on this: in some templates, the create project page will show everything (wizard, basic, fuinding ,story in vertical, instead of horizontal). do you have any idea? thank you!

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

You should use a template based on Twitter Bootstrap 2.3.
http://itprism.com/help/95-crowdfunding-documentation-faq#template_usage

Regards,
Todor
