### ISSUE TITLE
Will there be a BS3 version?

### ISSUE THREAD

**Issue by cantgetmyusername** [ITPrism/CrowdFunding#116]
BS2 breaks the templates I have been using for a while. I would hate to have to code around these kinds of issues at every turn to accommodate oldtechnology (yeah, I know, Joomla. Them too.)

![screenshot_986](https://cloud.githubusercontent.com/assets/5192979/3573974/617c7db8-0b78-11e4-9a27-58bae9b2f723.png)

**Comment by ITPrism** [comment]
Hi,
Thank you for the post and sorry for late answer!

It will be possible after Joomla! v3.7 because they are planning to implement Bootstrap 3 on that release.
http://developer.joomla.org/cms/roadmap.html

Regards,
T
