### ISSUE TITLE
CrowdFunding Image plugin + add field

### ISSUE THREAD

**Issue by nicolasfrance** [ITPrism/CrowdFunding#119]
Hi,

First, how CrowdFunding Image plugin is made for ?
Second, when you create a projetct, is it possible to add a field to send files like pdf, or doc openoffice docuement ?

thanks

nicolas.

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!
Sorry for late answer! 
Now it is possible to upload files like PDF, doc,...
You can do it using third-party extension CrowdFunding Files and project wizard in six steps.

Regards,
Todor
