### ISSUE TITLE
feature suggestion: priority level backer

### ISSUE THREAD

**Issue by jojouser** [ITPrism/CrowdFunding#129]
Does CrowdFunding pro support priority investor/backer? (Can be as an option: open priority level support or close priority level support. )
  For example, mainly crowdfunding project have some risk for Investor. some Investor can accept higher risk, some can accept low risk,
  then we can setup two level.
  the first/priority level investor/backer can accept higher risk and also have better priority benefits, but he should invest at least 10%(or other percent) of the amount of the crowdfunding project.
  the last/normal level investor can accept normal risk and also have normal benefits, and he don't have minimum investment amount.
  i think this is very useful. Will you implement this similar feature? thanks.

**Comment by ssnobben** [comment]
hmmm I dont follow you right here. 

Can you elaborate what you want to achieve and what to do? 

You want investors to have different "user groups type investor risks" and with that different privileges?
