### ISSUE TITLE
Database Error: 1062

### ISSUE THREAD

**Issue by cityhick** [ITPrism/CrowdFunding#131]
When I Launch a project, I get this -  Error: 1062

Duplicate entry 'http://www.famousbucks.com/create-project^[' for key 'idx_link_old' SQL=INSERT INTO `v9w76_redirect_links` (`old_url`,`new_url`,`referer`,`comment`,`hits`,`published`,`created_date`) VALUES ('http://www.famousbucks.com/create-project^[�][X[�Y�/��YLM', '' ,'http://www.famousbucks.com/create-project?layout=manager&id=16', '',1,0, '2015-01-13 23:31:31')

Anyone with any knowledge of this willing to help is greatly appreciated!

**Comment by ITPrism** [comment]
It seems, the component "Redirect" collects missing pages by the plugin "System - Redirect".
In your case, an URL exists and the plugin cannot insert a new record with the same URL.
If you would like, go to the component "Redirect" and remove old records. Let we see what will happen.
If you would like, you can also disable the plugin "System - Redirect".
![redirect](https://cloud.githubusercontent.com/assets/1272206/5735613/5cf0a4ec-9bd1-11e4-8340-c241fbadb767.png)

**Comment by cityhick** [comment]
That worked Todor! Thanks for the help!

**Comment by ITPrism** [comment]
Grate!

Have a nice day!
