### ISSUE TITLE
Database Error: 1054 (Unknown Coloumn) 

### ISSUE THREAD

**Issue by ironak** [ITPrism/CrowdFunding#136]
Well, I recently installed CrowdFunding 1.10 for Joomla 3.x and it seems there are number of database issues. I tried googling around but couldn't find a working solution. Below are some details.

Error: 1054
Unknown column 'a.image' in 'field list' SQL=SELECT a.id, a.title, a.description, a.amount, a.number, a.distributed, a.delivery, a.image, a.image_thumb, a.image_square FROM `q1tmr_crowdf_rewards` AS `a` WHERE a.project_id = 6

Extension Installed Version	1.10.1 Lite ( Stable )
PHP Built On	Linux gator3162.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version	5.5.40-36.1
Database Collation	utf8_unicode_ci
PHP Version	5.3.28
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

I guess, you have installed the extension before.
So, the tables still exists.
To fix that, you have to install old version and to install the new release over the old one.

Alternatively, remove all CrowdFunding tables manually. You have to remove the tables that contain prefix "_crowdf_". You can use phpMyAdmin to do that.
Then install the platform as clear installation.

Regards,
T

**Comment by ironak** [comment]
Thought so! Thanks man!
