### ISSUE TITLE
Project with more then 10000000 in funding goal

### ISSUE THREAD

**Issue by grigorovich-alex** [ITPrism/CrowdFunding#137]
Can't create project with more then 10000000 in funding goal. Goal which has more then 7 zeros saving only 10000000. How can i fix this? Is it db or library bug? Thank you.

**Comment by grigorovich-alex** [comment]
Oh! Find by myself. In db you can change parameter for field in decimalas - 10,3 to 1*,3

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!
Hmm...That is going to become really large amount. :)

Regards,
T

**Comment by grigorovich-alex** [comment]
I'm developing crowdfunding website for company in belarus. Exchange rates for 1 usd is about 15000 roubles. Project with funding goal over 10000000 byr = 667 usd. Not so much... ×
