### ISSUE TITLE
Is CrowdFunding version 1.11 Joomla 3.4 compatible?

### ISSUE THREAD

**Issue by ssnobben** [ITPrism/CrowdFunding#139]
Question: Is CrowdFunding version 1.11 Joomla 3.4 compatible? or when is it expected to be?

http://joomla.org/3/

rgds

ssnobben

**Comment by ITPrism** [comment]
Hi,
Yes, it is. I am doing the new release 1.12 over Joomla! 3.4 and it works well.
You can upgrade Joomla! to 3.4.0

Regards,
T

**Comment by ssnobben** [comment]
Good good Todor!

I will install Joomla 3.4 this week to and test. Had a 3.4 rc before and there was some javascript problem with EasySocial in backend only

Is version CF 1.12 coming with Royalty support too?

rgds

stephan



Date: Thu, 26 Feb 2015 01:16:32 -0800

**Comment by ssnobben** [comment]
If you want to test latest EasySocial with CF I have it too bcs I am subscriber there for Stackideas..

I can send it to you..

rgs

stephan




  

  

Date: Thu, 26 Feb 2015 01:16:32 -0800

**Comment by ssnobben** [comment]
Thats great I will check the new version with Royalty that will be exiting! All the best!

**Comment by ssnobben** [comment]
Hi

yeah I know have upgraded for Joomla 3.4 stable now had one issues here to install extensions.

Joomla 3.4 has this 
problem with some extension to install and it will fix in the next version of Joomla(3.4.1). i searched 
and in the below links(#2) you can find temporary solution before of 
releasing next version of Joomla.



Please check following pages which are related to this issue:

1) https://docs.joomla.org/J3.x:Extension_won%27t_install/en

2) https://www.rsjoomla.com/blog/view/294-fixing-the-joomla-340-extensions-installer-bug.html

When will dev of Royalty be included in CrowdFunding you think? is it much more to do to make it work?

rgds

stephan

  

  

Date: Thu, 26 Feb 2015 01:16:32 -0800

**Comment by ssnobben** [comment]
Hi Todor,

hope everything going great. Do you know when the new version will be released? I will make a subscription when that version is ready.

I also have an account here that you can check if you want some tips of UX etc

 https://www.crowdcube.se/login

user: ssnobben@hotmail.com  pw: 14141414

Hope to hear from you soon!

All the best!

stephan
