### ISSUE TITLE
Error last step no finalizing ?

### ISSUE THREAD

**Issue by ssnobben** [ITPrism/CrowdFunding#140]
Hi Todor

I did a project on your demo platform http://joomlafunding.com/raise?layout=rewards&id=339 and like before I wonder how you finalise the last wizard step to confirm it? 

You have no button or something to finalize the insert of project. Just save button for the steps...this issue I had before too and is very confusing.

Q: how to you finalize your project as an end user? 

rgs see attachment
![todorerror](https://cloud.githubusercontent.com/assets/6490832/6595315/8215922a-c7e9-11e4-8878-24716e1c87be.jpg)

**Comment by ITPrism** [comment]
Hi,
The demo uses too old version of the platform.

The new version provides a manager. :)
You can [download and install CrowdFunding Platform] (http://itprism.com/free-joomla-extensions/ecommerce-gamification/crowdfunding-collective-raising-capital) to test it.

![manager](https://cloud.githubusercontent.com/assets/1272206/6621697/ca030e9e-c8e0-11e4-8302-d4f2b5ef1417.png)

**Comment by ssnobben** [comment]
ok. So the front end wizard where a button for "Finalize" is fixed now bcs this was missing long time and I see that on your demo missing there too. Great! ps this is important fix so it work to finalize projects in the front end of project owners..
