### ISSUE TITLE
Bank Transfer email issues

### ISSUE THREAD

**Issue by VitjoMan** [ITPrism/CrowdFunding#167]
Hi, the Bank Transfer module freezes when I have the email templates assigned to it. Is there a way a user can stop their campaign when they have received the funds, or maybe inform us via the site that the payment has been received from the donor so we can take down the project? Please get back to me ASAP as my client is in a hurry to get their site running.

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!
Where it freezes? Could you attach a screenshot with notes, please?

The project owner can stop there campaigns from project manager and project list view.

![manager](https://cloud.githubusercontent.com/assets/1272206/15481046/46ecc5c2-2131-11e6-8a18-e337ecf1f1b7.png)

![projects_list](https://cloud.githubusercontent.com/assets/1272206/15481051/4df6d0f6-2131-11e6-878d-afbf37a56d1d.png)

**Comment by VitjoMan** [comment]
![screen shot 2016-05-23 at 9 14 27 pm](https://cloud.githubusercontent.com/assets/19537559/15481612/b68dde76-212b-11e6-957c-a20b2d1c916b.png)
 It freezes at the make payment, but this only happens when I try to include the email template. As for the stop this campaign it give an error when I try to stop it as the user. 
"Notice Sorry, but you cannot unpublish the project, because it has already approved." plus when I move my mouse over the table everything disappears, the Tittle, Goal, Funded etc and also the two ticks too. Could this be an issue with my template?

**Comment by VitjoMan** [comment]
Is there a video where I can learn to set up my pages to look like yours and have everything in the right place as you did. Cause Ive been struggling for the passed 2 days with this layout, I purchased premium membership so I can get all the plug ins and modules but I don't know how to make them work together for what I need to achieve. I tried to check your site but it only covers the basics.

**Comment by ITPrism** [comment]
You will find videos on the [quick start guide](http://itprism.com/help/119-crowdfunding-step-by-step).
I am going to do more videos.

To fix the bug with bank transfer you have to edit [line 15](https://github.com/ITPrism/CrowdFundingPayment-BankTransfer/blob/master/banktransfer.php#L15) in that file.

Replace EmailTemplates with Emailtemplates. Make 'T' lower-case.
plugins/crowdfundingpayment/banktransfer/banktransfer.php

**Comment by VitjoMan** [comment]
HEY, IT WORKS!! Thanx. Now my other issue about stopping the campaign on the user side. When I try to stop it as a user it gives the error "Notice Sorry, but you cannot unpublish the project, because it has already approved." How do I fix that?

**Comment by VitjoMan** [comment]
What I want to do basically is to have my user come back to the site to confirm when they received the money transfer, and only have the bar move when they received it...

**Comment by ITPrism** [comment]
Change the value of option ' Validate State Approved' to 'No' in plugin 'Content - Crowdfunding Validator'.

**Comment by VitjoMan** [comment]
Thank you that worked. You are very helpful, I appreciate your effort and I do not regret my Premium Membership on your site, it was a good buy! One more thing tho how do I solve the issue of the disappearing fields on the tables when I hover over them with a mouse?

**Comment by ITPrism** [comment]
Which fields? 
Could you send me a screenshot, please?

**Comment by VitjoMan** [comment]
I just asked a friend to check the site out. The projects and categories can not open on a mobile device, The links dont seem to work. Is the plug in not mobile friendly?

**Comment by VitjoMan** [comment]
![screen shot 2016-05-23 at 10 55 36 pm](https://cloud.githubusercontent.com/assets/19537559/15484266/81204112-2139-11e6-93f7-8bdcac4d6d62.png)
There you go, I hovered my mouse over a few so you can see what I mean.

**Comment by ITPrism** [comment]
It is mobile friendly. It depends on the template. 
You can test it in different size in Firefox. You should use CTRL + Shift + M to activate responsive design view.
If you would like you can try another template based on [Twitter Bootstrap 3](http://itprism.com/blog/96-joomla-boostrap-templates). Just for test to see it how it works.

About fields...you have to edit some styles of your template. If you would like, you can create account or send me credentials for one that I will be able to use. I will test and write you what you should edit in your CSS styles.

**Comment by VitjoMan** [comment]
Ok do you need the admin credentials?

**Comment by VitjoMan** [comment]
Oryt Ive had a look at the themes you linked to. I'll give them a go and see if they won't solve my CSS problem as well. On the email template I wanted to add some custom fields from Community Builder. It like it to show the user's banking details which is [cb_bankname] [bank_account] and etc so it pulls those from my database as part of my mail template. Which file should I edit?

**Comment by VitjoMan** [comment]
Hi sorry to bother you again. I went with the T3 Template but everything is just all over the place. it is possible for you to maybe send me the css file from the screen shot of the template that u took a screen shot of earlier so that I can use it as a guideline and costomize it accordingly. Im not really a pro when it it comes to such, I have basic level knowledge and when I see everything all upside down like that it's abit scary that I might break something...
