### ISSUE TITLE
Minimum Amount not working

### ISSUE THREAD

**Issue by VitjoMan** [ITPrism/CrowdFunding#168]
Hi please assist, I set my minimum amount to 500 but every time I type something lower it goes through successfully. I checked the validator, I checked wether the issue could be my payment module I dnt see any options there either. Please help the site is already online and my client is grinding me.

Can't I also auto stop the project when it gets to the goal?

**Comment by ITPrism** [comment]
Hi,
You should use option "Max Contributed Amount". You will find that option in Crowdfunding Finance, tab Fraud Prevention.

You have to enable the following plugins 
Content - Crowdfunding Fraud Prevention
CrowdfundingPayment - Fraud Prevention

Regards,
Todor

**Comment by ITPrism** [comment]
> Can't I also auto stop the project when it gets to the goal? 
There is no functionality that stops campaigns automatically when they reach the goal. However, that is good idea and I will implement it by a plugin and CRON job plugin for next release.

Thank you!
