### ISSUE TITLE
I think I complemented too soon

### ISSUE THREAD

**Issue by VitjoMan** [ITPrism/CrowdFunding#169]
Hi, Ive written to you asking questions about your plug in, Im having a disaster and you not coming to my aide. Ive had to struggle for a few days with it and you not coming to the party and helping out. Please cancel my "premium subscription" because it does not provide me with support as expected. I feel like the least you could do is answer my question. I'll have to find some other plug in that will work and Iam able to ask the developer any questions to get assistance to have my site running at its best. Please give me my refund. Thank you...

**Comment by ITPrism** [comment]
Hi,
Sorry about that!
It is the place where you should post information about issues. It is much more for developers.
I provide [premium support](https://members.itprism.com/support/forum) by the forum. I join here rarely. :)
I am going to refund you the money.

Best regards,
Todor
