### ISSUE TITLE
I can't see the donate buttons...

### ISSUE THREAD

**Issue by 21Vincent** [ITPrism/CrowdFunding#172]
My system:

JA Playstore 1.0.2
Crowdfunding 2.4.1
Library 1.14

I tried everything, from uninstalling to installing component, plugins, setting things up with bankaccount, and paypal, but nothing let me show the donate button? 

Do you have a suggestion?

**Comment by 21Vincent** [comment]
I figured it out, the template is just wrong for the extension. It would be nice if everything was on one module position, instead of severals... I will try to figure it out.

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!
You will have to assign the module **Crowdfunding Info** to a menu item.
Here you are more information.
http://itprism.com/help/119-crowdfunding-step-by-step#specific_modules_plugins

**Comment by 21Vincent** [comment]
Thanks it helped a lot!!! You are magic, and I am a noob, hahaha :)
