### ISSUE TITLE
HTTP ERROR 500 Admin Login

### ISSUE THREAD

**Issue by wj694** [ITPrism/CrowdFunding#176]
I am getting HTTP Error 500 when I log into the admin area, everything was fine until I added crowdfunding social community and crowdfunding categories.  The front end is fine.  I have tried changing my permissions for Administration Folder to 755 and 777 also tried changing the administrator/index.php file to both 755 and 777 no luck any suggestions?

**Comment by ITPrism** [comment]
Hmm...that is really strange.
It should be a problem with social community.
Could you find and disable the plugin **socialcommunityuser** in your database table **extensions**, please?
Let we see what will happen.
You can use phpMyAdmin. You will find it in your hosting control panel.

To find the row, you should search by column **element** 'socialcommunityuser'.

Current version of SocialCommunity is too old. Do not use it at the moment. It might have comparability issue with Prism Library.
I am going to upload the new version of SocialCommunity in next few days.

**Comment by wj694** [comment]
Yes, this worked thank you
