### ISSUE TITLE
Payment error with Sripe Connect

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#179]
Hi Todor.
I'm near to activate a subscription in order to download the extensions of your new version of crowdfunding platform. Meantime, I'm doing some test tasks using the 2.5.1 version.

Considering PayPal policy changes I'm testing Stripe Connect. 
I followed your documentation but, at the end of the payment process, i get the error that you can see in this attached image:

![paymenterror_1](https://cloud.githubusercontent.com/assets/4001128/19014312/69a50d84-87ea-11e6-9ca4-25eb093d0f99.PNG)

I don't know if it's a bug or any kind of my mistake...

Thanks in advance!

Giuseppe.

**Comment by ITPrism** [comment]
Hi ,
Which version of Stripe Connect do you use?

Could you download and install latest one.
http://itprism.com/free-joomla-extensions/ecommerce-gamification/crowdfunding-collective-raising-capital

You have to update Crowdfunding Finance too.

**Comment by gpalmas** [comment]
I'm using:

Crowdfunding Finance v.2.4
Crowdfunding Component v.2.5.1
Stripe Connect v.1.2
Prism Library v.1.16
Prism Library - Italian (Italy) v.1.1

I still getting the same error... :-(

**Comment by ITPrism** [comment]
For CF v2.4 you should use Stipe Connect v1.1 because they are not compatible.
I did major upgrade that is not compatible.

http://cdn.itprism.com/extensions/crowdfunding/plg_crowdfundingpayment_stripeconnect_v1.1.zip

You should use Prism Library 1.14
cdn.itprism.com/extensions/library/lib_prism_v1.14.zip

**Comment by ITPrism** [comment]
Could you check the URL in your Stripe platform, please?

It should look like this

http://devcf.itprism.com/index.php?option=com_crowdfundingfinance&task=payouts.authorize&payment_service=stripeconnect

Replace http://devcf.itprism.com with your domain.
![stripe_redirect_url](https://cloud.githubusercontent.com/assets/1272206/19018839/8906e25e-8878-11e6-852f-ce75716223da.png)

**Comment by gpalmas** [comment]
Yes, the redirect url in my Stripe account is: http://www.eclent.com/j3/index.php?option=com_crowdfundingfinance&task=payouts.authorize&payment_service=stripeconnect

But, I'm thinking... I installed Joomla in a subfolder named "j3" and I'm not sure that the redirection can work also in this case. Anyway I'm sending you, by email, the access credentials of the Joomla admin account.

Thanks a lot!

**Comment by ITPrism** [comment]
I have just fixed it and upgraded it on your site. You can try it.
https://github.com/ITPrism/CrowdfundingPayment-StripeConnect/commit/1a7b70c415cbbade19e0bcf237dd6d5ea785b624

The problem was in the URL in the form.

**Comment by gpalmas** [comment]
Yes, I made some tests and it seems that it's working correctly.
Thank you Todor! I let you know if I will discover other bugs.
Have a nice day!
