### ISSUE TITLE
User Registration Failed

### ISSUE THREAD

**Issue by wj694** [ITPrism/CrowdFunding#182]
I am trying to create a test account, when I try to register a new user I am getting the following: 

Warning

Field required: Frontend Language

I have English-US set as the default language, and have English-US, English-GB, French and Spanish languages installed.

**Comment by ITPrism** [comment]
It seems, it may be a problem with Joomla User Manager settings.
Could you try that solution, please?

http://www.function90.com/support/joom-profile/278-registration-failed-field-required-frontend-language.html#1253

**Comment by wj694** [comment]
Problem solved thank you
