### ISSUE TITLE
Fatal error when loading images

### ISSUE THREAD

**Issue by wj694** [ITPrism/CrowdFunding#183]
I have found another error when creating a test campaign.  I uploaded a main image and am now getting the following error when I am on the manager page. The image I uploaded does not show even though it was showing on the "Basic" page of the wizard.  Error I am getting:  

Fatal error: Class 'CrowdFundingImages' not found in /home/filename/sitename/plugins/content/crowdfundingimages/crowdfundingimages.php on line 65

I also do not have the multiple image feature in the options --> media tab

**Comment by ITPrism** [comment]
Could you disable the plugin **Content - Crowdfunding Image**, please?
I stopped using it and removed the gallery from the crowdfunding platform.
You will have to use [Crowdfunding Gallery](http://itprism.com/help/95-crowdfunding-documentation-faq?start=3#plugins-crowdfunding-gallery) to provide galleries on your website.

**Comment by wj694** [comment]
I disabled Content - Crowdfunding Images,  I still have Content - Crowdfunding Gallery, Crowdfunding Gallery Package, Magic Gallery, Magic Gallery Library, Magic Gallery Package, Magicgallery Camera, Magicgallery Galleria, and Magicgallery Slide Gallery active.  

The error is gone but the image is still not showing. I have tried uploading the image again and no luck.  I also verified that I have images/crowdfunding installed in my cpanel.  The image does show in this folder bu not showing on my test site. I have tried loading a different image and no luck.  I also have a video linked to you tube and this is working.  

I have verified that I have the updated versions of both the free extensions and premium extensions.  Also I still do not have the option of adding extra images.

**Comment by ITPrism** [comment]
1. Create category "Crowdfunding" in the extension "Magic Gallery".
2. Enable Crowdfunding project **wizard in six steps**. You can do it on the crowdfunding platform options, tab Project Wizard.
3. Enable the **plugin Crowdfunding - Gallery**. Open the plugin to access its options and select the category that you have just created in Magic Gallery. Now, you will be able to upload pictures on step "Extras" of the project wizard.
4. Enable the plugin Content - Crowdfunding Gallery. That will show the pictures on your campaign details page.

![gallery](https://cloud.githubusercontent.com/assets/1272206/19769589/b7b3556a-9c64-11e6-8f22-388007796dd2.png)

**Comment by wj694** [comment]
Still nothing, message received : "Fail - Invalid Gallery"  I have tried png, jpg and gif images

**Comment by ITPrism** [comment]
Did you select the category in the plugin "Crowdfunding - Gallery"?
If you would like, you can send me username and password for your administration. I will check it for you.
You can do it to my email todor@itprism.com

![category](https://cloud.githubusercontent.com/assets/1272206/19771397/7661be38-9c6b-11e6-8aff-26a67d66e5f9.png)

**Comment by wj694** [comment]
I just emailed you all the information

**Comment by wj694** [comment]
Thank you the gallery is working now, but is this the way the manager screen should look
![screenshot 3](https://cloud.githubusercontent.com/assets/15555432/19773832/98526c62-9c30-11e6-9001-9e0ef99f0714.png)

**Comment by wj694** [comment]
can you look at both the screen shots below

this is the settings on the media page of the crowdfunding options it shows the images are stored in the images/crowdfunding  file

![screenshot 5](https://cloud.githubusercontent.com/assets/15555432/19776495/e54b36d0-9c39-11e6-95ba-c65cc61bfdb2.png)

the second is from the inspect element section it shows the image should be coming from /media/com_crowdfunding/images/  could this be the issue with the main image?

![screenshot 4](https://cloud.githubusercontent.com/assets/15555432/19776561/1ec70420-9c3a-11e6-9fbb-d6e9462c3420.png)

**Comment by ITPrism** [comment]
In your case, it shows a picture no_photo.png because you have not uploaded a picture for the campaign.
You will have to upload a picture on **first step "Basic"** and crop it.
If the functionality does work on first step, check for JavaScript errors. It could be a reason browser to block initialization of scripts.
If there is JavaScript error, find a way to fix it.

**Comment by wj694** [comment]
Yes everything works now!!! I updated jquery to 1.1, which fixed the errors and also found out the image I was uploading was too big since I did not use the crop image feature thank you for everything you are the best!!!
