### ISSUE TITLE
Fatal Error with Crowdfunding Info

### ISSUE THREAD

**Issue by wj694** [ITPrism/CrowdFunding#185]
I am receiving the following when I click on the test campaign on the Discover page

 "Fatal error: Call to a member function isVerified() on a non-object in /home/dropfund/test3.dropfunding.com/plugins/content/crowdfundinginfo/crowdfundinginfo.php on line 81" 

I checked no jquery errors 

This happened after following the video "How to set up some of the main CrowdFunding plugins and modules?"

**Comment by wj694** [comment]
I think I found the issue plugins -->crowdfundinginfo on the "user tab" if the "Display Account State" is selected to Yes it causes the error if I select No it fixes the issue

**Comment by ITPrism** [comment]
Right. You should use that option with [Proof of Identity](http://itprism.com/free-joomla-extensions/ecommerce-gamification/verifying-user-profile).
