### ISSUE TITLE
Placeholder for Bank Transfer IBAN code

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#191]
Hi Todor.
There is a placeholder that I can use in an email template, in order to dinamically generate the IBAN code of a project owner in the email sent to it's baker?
It seems not. Or am I missing something?
Thanks in advance!

**Comment by ITPrism** [comment]
Hi Giuseppe,
You should use {TRANSACTION_ID}.
The generated code that the user should submit as grounds for remittance is transaction ID.

![email_template](https://cloud.githubusercontent.com/assets/1272206/20578422/e86d5eaa-b1cf-11e6-8105-0674769b8fba.png)

Best regards,
Todor

**Comment by gpalmas** [comment]
Yes, that already works. The transaction ID is correctly passed to the email sent. But I was not referring to that. I mean the IBAN code. It is manually written, directly in the email template. In a multi-owner scenario it would be useful to have a placeholder to pass to the email also the owner's IBAN code, because each owner has a different IBAN.

**Comment by ITPrism** [comment]
I did it for in last release.
