### ISSUE TITLE
Suggestion: payment wizard improvement

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#192]
Hi Todor!

During the payment process, it would be useful to allow the donor to login AND also allow him to enter his address (useful to deliver rewards at the end of the campaign).
But, as I seem to see, the plugin "CrowdfundingPayment - Login" and "CrowdfundingPayment - Data" can't work together.

A potential solution would be to display the data input form of the plugin "CrowdfundingPayment-Data" (perhaps with a refresh of the same tab) after the user has logged-in through the plugin "CrowdfundingPayment-Login". In this way, the user would not be forced to login by leaving the payment form and, at the same time, it would be possible to collect his address in "Crowdfunding Data", in order to easily associating it to his account.

I think this may further simplify the payment process. As one of our customers expressed this need, I thought I might ask you to develop specifically for us a plugin which does the two things together and that could replace the development. We could pay to develop it, in the near future.

Best regards!

**Comment by ITPrism** [comment]
Hi Giuseppe,
I agree with you. I am planning to improve the payment wizard. I will definitely use your suggestions and to implement them in next release.
Thank you very much!

**Comment by gpalmas** [comment]
Thank you! I'm doing some tests and I'm collecting infos and impressions. Sorry if I'm opening many tickets but I believe that it is useful for you, in order to collect all the suggestions so you have ideas to improve the platform.

**Comment by ITPrism** [comment]
All is OK. I am really grateful for your suggestions. I would like to do the platform useful for many people and very one helps me with their ideas and suggestions.
Thank you very much!

**Comment by ITPrism** [comment]
I did it for in last release.
