### ISSUE TITLE
Skip Payment Process

### ISSUE THREAD

**Issue by EsPi87** [ITPrism/CrowdFunding#193]
Dear developer Team,

is it possible to skip the Payment process?
We don't need to fund an amount of money. We want to catch people into Groups for different Projects so we just need a verification process (join project only for logged in people).
Thanks in advance

**Comment by ITPrism** [comment]
Hi,
Yes, it is.
You can change the payment wizard [overriding the layouts.](http://itprism.com/help/120-crowdfunding-developers-documentation#edit_views).

You can also override the module [Crowdfunding Info](https://github.com/ITPrism/CrowdfundingDistribution/tree/develop/modules/mod_crowdfundinginfo) that points to the payment wizard. You can do it sending your users to another component developed by you.

You can also do your own payment plugin that will verify your users. You should use [paymen plugin events](http://itprism.com/help/120-crowdfunding-developers-documentation).
