### ISSUE TITLE
Possible bug: duplicated notification emails

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#194]
Hi!
I think I found a bug...

I've enabled the Stripe Connect plugin and the Bank Transfer plugin together. I've also set the related email templates.

When an user makes a donation using the Bank Transfer plugin, he receives a confirmation email correctly. Instead, if the user makes a donation using the Stripe plugin only, he receives two confirmation emails: one correctly related to his donation made with Stripe and another related to the bank transfer plugin also. This is incorrect...

It seems that the bank transfer plugin interferes at the end of the Stripe payment process.
What do you think about it?

Best regards!

**Comment by ITPrism** [comment]
Hi!
You are right. I have to fix that in Bank Transfer.
Thank you very much!

Best regards,
Todor

**Comment by gpalmas** [comment]
Thank you!

**Comment by gpalmas** [comment]
Ok, it's working very well!
Thanks!
