### ISSUE TITLE
Fatal error when capturing transactions

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#195]
Hi Todor.
I'm getting the following error when I try to capture some Stripe transactions in CF Finance:
Fatal error: Class 'GuzzleHttp\Client' not found in /web/htdocs/www.eclent.com/home/j3/libraries/Prism/libs/League/OAuth2/Client/Provider/AbstractProvider.php on line 123

Do you have any idea?
I'm running the latest version of Joomla and all the Crowdfunding scripts are updated...

**Comment by ITPrism** [comment]
Hi Giuseppe,
I guess, it is a problem with not loaded GuzzleHttp Library.
You should edit that file **_plugins/crowdfundingpayment/stripeconnect/stripeconnect.php_**

Add the following code at the beginning of the file.
`jimport('Prism.libs.GuzzleHttp.init');`

I am going to check and fix CF Finance.

![guzzle_init](https://cloud.githubusercontent.com/assets/1272206/21734493/55d76a9e-d46c-11e6-94d1-671199525c65.png)

**Comment by gpalmas** [comment]
Thank you Todor, now it's working correctly!
Best regards.
