### ISSUE TITLE
Possible bug in new payment process

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#198]
First of all, thank you so much for all the work done for the release of the new features!
I think I found a bug in the new donation process.
After entering the amount you are correctly redirected to the second step, in order to insert additional data via the CF Data plugin. However, when you click on the "Continue to next step" button, after having already saved the entered data, you are redirected back to step 1 and not to step 3 (to log in).
I'm not sure if this is a bug or my configuration error.
I also tried to disable all my template overrides but the issue remains...
If you want to reproduce the error, you can check here: https://www.eclent.com/j3/crowdfunding

**Comment by gpalmas** [comment]
Update: I tried to clear the website cache and the cookies from my browser and now when I click on the "Continue to next step" button, after having already saved the entered data, I'm correctly redirected to the step 3 (login).
But now I have another issue: after log in i'm redirected to the step 1. Then, the data entered in the previus step 2 (CF Data) are lost and needs to be re-entered...

**Comment by ITPrism** [comment]
You can reorder plugins and move Login to step 2.
You can disable CrowdfundingPayment - Data for registered users.

![reorder_plugins](https://cloud.githubusercontent.com/assets/1272206/23355595/224f7e3c-fcdf-11e6-8e8e-a9ee943b0039.png)
![show_to_registered](https://cloud.githubusercontent.com/assets/1272206/23355631/497c69e8-fcdf-11e6-811a-6f28c87e7f35.png)

**Comment by gpalmas** [comment]
Ok, I solved by set the plugins order as you suggested.
Thanks a lot!
