### ISSUE TITLE
Bank Transfer plugin error

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#201]
Hi Todor!
After last upgrade, I'm getting an error with Bank Transfer also.
In the payment selection page, when I click on the Bank Transfer button (and confirm in the popup) I see a message like "The system cannot process the transaction".
The url is: https://www.eclent.com/j3/crowdfunding
You can use the following credentials to login as a test donor:
User: testuser
Password: orioladu

Thank you and best regards!

**Comment by ITPrism** [comment]
It may make a transaction to wrong URL.

Could you edit '**plugins/crowdfundingpayment/banktransfer/js/script.js**', please?
You will have to add /j3/crowdfunding/ to the link on **line 18**.

![bank_transfer_url](https://cloud.githubusercontent.com/assets/1272206/23394360/50d73b7a-fd91-11e6-8e77-d2e5c2195f6c.png)

**Comment by gpalmas** [comment]
Done, but I still get the same error. Do you want to access to my test environment in order to make some tests as an admin or to directly edit files?

**Comment by ITPrism** [comment]
Yes, I do.
If you would like, you can install [ProFiles](https://extensions.joomla.org/extension/profiles/) and enable [Joomla! debug](http://itprism.com/help/95-crowdfunding-documentation-faq#debug).

You can send username and password to my email todor@itprism.com

**Comment by gpalmas** [comment]
Hi todor!

In order to investigate about issues #199 and #201, I send you the admin
credentials of my Joomla test environment:

Admin url: http://www.eclent.com/j3/administrator
User: admin2
Password: adm2pwd

ProFiles is installed, debug is enabled and the default language of admin2
account is set to english.

Thank you and best regards!


*Giuseppe Palmas*

Mail: giuseppe.palmas@gmail.com
Linkedin: http://it.linkedin.com/in/palmas
Web: http://www.mycityup.com

2017-02-28 15:59 GMT+01:00 Todor Iliev <notifications@github.com>:

**Comment by iz29** [comment]
Having the same error
I have done what is suggested.
But it keeps loading

**Comment by ITPrism** [comment]
Giuseppe, please, do not post credentials here. It is public and everyone can see it. :)
I am going to check it bank transfer.
Please, change the username and password because some can install viruses on your website. :(

**Comment by ITPrism** [comment]
I found the issue. I am going to fix it. It sees, the system does not create payment session when the plugin CrowdfundingPayment - Data is enabled.
Thank you very much!
Do not forget to change your passwords on your website. :)

**Comment by iz29** [comment]
thanks for the reply ^^

**Comment by gpalmas** [comment]
Thank you Todor!
The credentials are not a problem because it's only a test environment. Everytime I have to transfer any change in production I do it manually, with a diff comparison of edited files and DB tables only.
Now I'll wait your fix.
Thank you very much!

**Comment by gpalmas** [comment]
P.S.:
Otherwise, I have disabled the admin2 account.
You can tell me if you need to do some tests and I can resend you the new credentials by email...

**Comment by gpalmas** [comment]
Now it's working for me. Thank you!
