### ISSUE TITLE
CF Files not working

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#206]
Hi!
I installed the CF Files component but I can't see the related step in project creation/editing wizard.
All the 2 related plugins are enabled, rewards are disabled and the wizard is already set to six steps.
I'm not sure if the issue is related to the step of payment methods or my mistake.
In order to improve it, is possible to call the form directly inside the story editing page instead of in a separate tab of the wizard?

**Comment by ITPrism** [comment]
Hi,
Hmm...that is strange. It is enough to select **Project Wizard** in six steps and to enable the plugin Crowdfunding - Files.
Have you [overridden plugin layout](http://itprism.com/help/120-crowdfunding-developers-documentation#edit_views)?
plugins/crowdfunding/files/tmpl/default.php

If it has been overridden, it could be a problem and you should replace old layout with the new one in your template folder.

![enable_plugin](https://cloud.githubusercontent.com/assets/1272206/24074696/48c2e09a-0c16-11e7-9852-d932af3ebcd3.png)
![extras_files](https://cloud.githubusercontent.com/assets/1272206/24074697/48c2f580-0c16-11e7-9da5-e52613d998c7.png)
![project_wizard](https://cloud.githubusercontent.com/assets/1272206/24074698/48c38b6c-0c16-11e7-90d0-d7c705dd579c.png)

**Comment by ITPrism** [comment]
> In order to improve it, is possible to call the form directly inside the story editing page instead of in a separate tab of the wizard?
That is good idea and I like it. I can add option to the plugin that you will be able to select where to show Crowdfunding - Files form.

**Comment by gpalmas** [comment]
Sorry Todor, it was my mistake! I confused two test environments. I tried the component in the correct envitonment and it works.
Thank you!
