### ISSUE TITLE
New bug with unpulish a project

### ISSUE THREAD

**Issue by flnative** [ITPrism/CrowdFunding#21]
If you have one project and go to the back end to publish it. The menu item for projects throws this error on the front end (see below). You cannot unpublish from front end if the project is already approved. Why?  (as mentioned in another thread, you cannot edit a project from the front end or add more rewards.)

The page isn't redirecting properly
        
          Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

**Comment by ITPrism** [comment]
Fixed.
