### ISSUE TITLE
How to lock edition of old rewards

### ISSUE THREAD

**Issue by julienduhavre** [ITPrism/CrowdFunding#211]
Hi, I'm trying to lock edition of old rewards in the "edit project" section.
But I want to leave the possibility of adding new ones.

How can I edit that ?

Thank you very much :)

**Comment by julienduhavre** [comment]
I rely on the Validator plugin, but I do not think I have the skills to do it. Who can help me :) ?

**Comment by ITPrism** [comment]
Hi,
Hmm... 
There is no validation event in the process of rewards adding.
I may have to add one. :)

If you would like, you can edit method **save()** the controller.
_components/com_crowdfunding/controllers/rewards.php_

or the method **validate()** in the model _components/com_crowdfunding/controllers/rewards.php_

best solution will be to add an [plugin event onBeforeRewardsSave](https://docs.joomla.org/Supporting_plugins_in_your_component) in the method save() in the model on line 130.

[Do a plugin](https://docs.joomla.org/J3.x:Creating_a_Plugin_for_Joomla) that will check if a reward has an ID. If there is an ID, exclude the item from the array.

If should be

_JPluginHelper::importPlugin('content');

$dispatcher = JEventDispatcher::getInstance();
$dispatcher->trigger('onBeforeRewardsSave', array('com_crowdfunding.project.wizard.rewards', &$data));_

I will add this event in next release. Your plugin will work properly.

![on_before_rewards_save](https://cloud.githubusercontent.com/assets/1272206/25646847/22201b88-2fc5-11e7-8570-4d41656d67a3.png)

**Comment by julienduhavre** [comment]
Thank you ! I will try that asap and get back to you if it work (and why not send the code 😄 )

**Comment by julienduhavre** [comment]
After 6 days, I think I have not the skill to do that..
