### ISSUE TITLE
Multilingual categories

### ISSUE THREAD

**Issue by julienduhavre** [ITPrism/CrowdFunding#215]
Hello, I want to have two categories (in French and in English). 
If during the creation of the category, I select language = French for example, on front-end, the category show up despite if I'm in french or in english.

How can we implement the multilingual ? Thank you 😃

**Comment by ITPrism** [comment]
Hi Julien,
There is no functionality to use the crowdfunding platform in several languages at the moment. Sorry!
I hope to implement it soon.

**Comment by julienduhavre** [comment]
Ok 😄  Thank you for reply
