### ISSUE TITLE
Error during the process of project creating

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#216]
Hi Todor!
I have a throuble and I'm worried because I have to go live tomorrow with my website! :-(
The issue is: when I try to create a new project in the frontend (logged as Super User also), I get the error "There was an error during the process of project creating".
In the backend I can see that the project is saved.
The address is: https://www.eupuru.eu/nuovo-progetto-eufund
Canyou help me? Thanks a lot!!!

**Comment by ITPrism** [comment]
Hi Giuseppe,
Hmm...that is strange. It seems, there is a problem with a **content plugin**.
If you would like, you can [enable debug mode](http://itprism.com/help/95-crowdfunding-documentation-faq#debug). The system will store information about the error in its log files.
That will give more information about the problem.

Alternatively, you can start disabling plugins one by one to see which occurs the error.

You can disable the following ones.

Content - Crowdfunding Admin Mail
Content - Crowdfunding User Mail
Content - Crowdfunding Validator

![content_plugins](https://cloud.githubusercontent.com/assets/1272206/25754745/07dfff12-31c9-11e7-8c54-9ec04382e429.png)

**Comment by gpalmas** [comment]
Ok, I tried by disabling the CF related plugins one by one but I get the same error... :-(
Then I also tried to enable the debug mode (following your guide) but after getting the error I have no files in /log and in /logs.
It's very strange!
I tried to look in the log section of the CF component but it seems that there are no useful infos.
Could there be a conflict with a thirdy part plugin?

**Comment by gpalmas** [comment]
Good news Todor!
I found the problem: it was a conflict with the pluging "Content - EasyDiscuss" that allows to integrate the discussion system of EasyDiscuss into the articles created in EasyBlog.
I can leave it disabled for now because it is not working well (some buttons are non working) and I have already sent a throuble ticket to the developer in past days.
But, when they will solve all the issues I will need to enable it because it gives me a key feature for my project needs!
Do you know if there is any way to disallow a plugin in selected pages or views, such as the views of CF platform?

**Comment by gpalmas** [comment]
Hi!
I solved this issue with the help of the developers of the plugin that caused the conflict.
Then, I can close it!
