### ISSUE TITLE
0 Too few arguments to function Prism\Money\Money: error

### ISSUE THREAD

**Issue by ssnobben** [ITPrism/CrowdFunding#228]
Hi Todor

I also now tried to reinstall latest CrowdFund 2.6.5, latest updated IT Prism liberary and CrowdFinance with l Joomla 3.8 and got this error for both in backend. 

Can not go to CrowdFunding backend and get this error there. Both crashed

0 Too few arguments to function Prism\Money\Money::__construct(), 1 passed in /home//public_html/libraries/Crowdfunding/Helper/MoneyHelper.php on line 82 and exactly 2 expected 

Rgds

**Comment by ITPrism** [comment]
Hi Stephan,
You have to use Prism Library 1.19

All the best!

**Comment by ssnobben** [comment]
Thanks Todor! Hope things going well for you. Cheers!
