### ISSUE TITLE
Button invest to a project is not shown

### ISSUE THREAD

**Issue by brainer94** [ITPrism/CrowdFunding#231]
I try to use this module.
I can create project and publish it, but i don't know how to donate to a project because donate button is not shown.
You can see in my domain : http://crowdnesia.com/
Could you help me with this problem ?

**Comment by ITPrism** [comment]
Do not post username and password here. It is publish forum. It is visible for everyone. :)
You will have to enable and show module Crowdfunding Info.
Here you a video that will show you how to do it.

http://itprism.com/help/119-crowdfunding-step-by-step#specific_modules_plugins

**Comment by brainer94** [comment]
I already did, but still an error "Invalid project" occurred ...
Really confused ...
Do you have any clue ?
Btw, that is only my testing environment, i will change all password after all :)

**Comment by ITPrism** [comment]
Could you send me username and password for your dev env, please?
I will check and write you about your issue.
