### ISSUE TITLE
CRON error occurred

### ISSUE THREAD

**Issue by gpalmas** [ITPrism/CrowdFunding#235]
Hi Todor.
Yesterday I tried to configure and enable the CRON feature in order to notify users about news of a project.
Today morning the job started and the webserver dropped the following error:
 
Crowdfunding CRON
============================
notify context: com_crowdfunding.cron.notify.updates
============================

Notice: Undefined index: id in /home/eupuru56/public_html/libraries/Crowdfunding/Projects.php on line 313
Total Processing Time: 0.398 seconds.

Do you have any idea about this issue?
Thanks a lot!

**Comment by ssnobben** [comment]
gpalmas  great that you bughunting. thanks for your help and work here

**Comment by gpalmas** [comment]
Update: Today the scheduled CRON started again and sent the messages correctly without any error.
In the meantime, I have not made any changes on the previous configuration.
I do not know why the problem manifested itself yesterday, but now everything seems to be working well!
