### ISSUE TITLE
Issue with CrodfundingFinance 2.6 

### ISSUE THREAD

**Issue by chuchichaeschtli1** [ITPrism/CrowdFunding#249]
I have Installed Crowdfunding 2.7 and CrodfundingFinance 2.6, with Prisma Library 1.22.
Unfortunaly i can't save individual Payment Datas. 
If i save the form with the IBAN and Banking Informations, it gives me this error.

Call to undefined method Prism\Date::toSql()

If i check the SQL Table, the informations are not stored in it.
Its strange, that the first ever createt IBAN data in CrodfundingFinance has been stored, but there is no possibility to store additional Datas.

**Comment by chuchichaeschtli1** [comment]
Here is also an Error Screenshot, after saving the datas
![error](https://user-images.githubusercontent.com/38275709/38621517-514c4b76-3da1-11e8-948f-6281dc04874d.PNG)

**Comment by mrGorion** [comment]
Sorry to bring the bad news but this project seems no longer supported.........
I've been trying to get some feedback for 5 or 6 months now.....
