### ISSUE TITLE
Mollie Payment error

### ISSUE THREAD

**Issue by bartiest** [ITPrism/CrowdFunding#259]
Mollie has changed his API. So the module doesn't give any status update and payments aren't registered in the backend. Even when payments are complete.

Is this module still developed?

**Comment by Rakeshmvd** [comment]
Try this at line 240:
Replace
`// Set real status ( the bank payment status ) and consumer name as additional data.
            $transactionData['extra_data'] = array(
                'mode'   => $payment->mode,
                'method' => $payment->method,
                'createdAt' => $payment->createdDatetime,
                'status' => $payment->status,
                'paidDatetime' => $payment->paidDatetime,
                'canceledAt' => $payment->cancelledDatetime,
                'expiredAt' => $payment->expiredDatetime,
                'links' => $payment->links
            );`

with
`// Set real status ( the bank payment status ) and consumer name as additional data.
            $transactionData['extra_data'] = array(
                'mode'   => $payment->mode,
                'method' => $payment->method,
                'createdDatetime' => $payment->createdDatetime,
                'status' => $payment->status,
                'paidDatetime' => $payment->paidDatetime,
                'cancelledDatetime' => $payment->cancelledDatetime,
                'expiredDatetime' => $payment->expiredDatetime,
                'links' => $payment->links
            );`

and 

replace
`// Set completed because the paid status is TRUE.
            if (strcmp('paid', $payment->status) === 0) {
                $transactionData['txn_status'] = 'completed';
            } elseif (strcmp('cancelled', $payment->status) === 0) {
                $transactionData['txn_status'] = 'cancelled';
            } else {
                $transactionData['txn_status'] = 'pending';
            }`

with
`// Set completed because the paid status is TRUE.
        if (strcmp('paid', $payment->status) === 0) {
                $transactionData['txn_status'] = 'completed';
            } elseif (strcmp('cancelled', $payment->status) === 0) {
                $transactionData['txn_status'] = 'cancelled';
            } 
			elseif (strcmp('failed', $payment->status) === 0) {
                $transactionData['txn_status'] = 'failed';
            } 
			
			elseif (strcmp('expired', $payment->status) === 0) {
                 return null;
            }
			elseif (strcmp('refunded', $payment->status) === 0) {
                $transactionData['txn_status'] = 'refunded';
            }
			
			else {
                $transactionData['txn_status'] = 'pending';
 				return null;
            }`

**Comment by Rakeshmvd** [comment]
Also check some other BUG FIXES
