### ISSUE TITLE
set max goal for project

### ISSUE THREAD

**Issue by dimioctora** [ITPrism/Crowdfunding#5]
hello i used ITPrism crowdfunding for my website but there is any problem when i test on submit for a project..
everything is okay till i input a goal on raise of fund,, i put it on (indonesia rupiah) Rp. 200.000.000,- but when i save and continue why the goal is set on Rp. 10.000.000?
i have changed for back end administrator > crowdfunding > options (tab project wizard) > minimum n maximum goals is zero,, but still same problem..
what should i do ? please help me,,

**Comment by ITPrism** [comment]
You should change the maximum number of digits of the [decimal columns](https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html) "goal" and "funded". :)
You fill find those columns in table #__crowdf_projects. :)

![Screenshot](https://user-images.githubusercontent.com/1272206/81973443-d4bb6600-962c-11ea-9538-6e364afdf14d.png)

**Comment by dimioctora** [comment]
ok, i changed the database table and thts solved..
thanks so much..
