### ISSUE TITLE
Crowd funding "type" not shown up in front end when creating a project..

### ISSUE THREAD

**Issue by ssnobben** [ITPrism/CrowdFunding#96]
Hi Todor, 

the new crowd funding type is good improvement idea and you can create these crowd funding types in the back end. 

But you can not set them up when you create a crowd funding project and there is no filter for it to on a Discover projects too. 

So maybe there is some not ready/missing developed issues there? Or how would I use "Types" when a end user can not set up that in front end when creating a project? as now they are nowhere bcs I cant see any option of that in new J 1.6 lite version...

all the best!

**Comment by ssnobben** [comment]
Hi Todor, glad that you are back and have closed some issues. 

Just take long time for responses so people maybe get reluctant to go ahead for Crowd funding?...will see if I start up again with a new Crowd funding project if progress here is good  :) 

all the best! 

Btw is this fixed now?

**Comment by ITPrism** [comment]
Hi,
I guess, you have found the drop down select element on the "**Basic**" step. :)

I am planning do a module and plugin that display the type name. :)

![project_type](https://cloud.githubusercontent.com/assets/1272206/6547053/83790762-c5d4-11e4-8996-9743cfc0a2d1.png)

Cheers,
Todor

**Comment by ssnobben** [comment]
Hi Todor,

I just see that update of 1.11.1 and dl the free version. I will test it beginning next week and then go for pro version when the Royalty is ready!

Great great!

Talk later!

stephan

  

  

Date: Sun, 8 Mar 2015 11:48:55 -0700
